name: copilot-deploy-infra

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_OPENAI_ENDPOINT:
        required: true
      OPENAI_KEY:
        required: true    
    outputs:
      deployment-id:
        description: "The Id of the current deployment."
        value: ${{jobs.deploy.outputs.deployment-id}}

jobs:
  deploy:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }
    outputs:
      deployment-id: ${{steps.deployment-id.outputs.deployment_name}}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Generate Deployment Id
        id: deployment-id
        run: echo "deployment_name=${{ vars.CC_DEPLOYMENT_NAME }}-$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}}
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          enable-AzPSSession: false
          allow-no-subscriptions: true

      - name: deploy-infra
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            scripts/deploy/deploy-azure.sh -d deployment26 -s ${{secrets.AZURE_SUBSCRIPTION_ID}} -aikey ${{secrets.OPENAI_KEY}} -c ${{secrets.AZURE_CLIENT_ID}} -t ${{secrets.AZURE_TENANT_ID}} -fc 9437e65c-7110-41f3-9b03-a2a78641ffbb -ai OpenAI